---
title: "Assessment 00 (Practice)"
author: "STAT414"
date: "2024-12-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(EnvStats)
# 1. we use the two-sample t-test to compare sulfate concentrations (EPA.09.Ex.16.1.sulfate.df)
# at a background and downgradient well.
data <- EPA.09.Ex.16.1.sulfate.df
data
# (a) Use the appropriate EnvStats function to compute the t-test. Show all seven steps
# of the statistical hypothesis testing procedure clearly. The resulting t-statistic is
# 5.66 with 12 degrees of freedom.
  t.test()
# (b) Plot the pdf of a t-distribution with 12 degrees of freedom and add a vertical line
# at x = 5.66.

# (c) Explain what part of this plot represents the p-value for the test of the null
# hypothesis that the average sulfate concentrations at the two wells are the same
# against the alternative hypothesis that the average concentration of sulfate at the
# downgradient well is larger than the average concentration at the back-ground
# well. In the same plot, illustrate the power of the t-test for a specific value in the
# alternative.

# 2. Consider the copper concentrations stored in the data frame EPA.09.Ex.16.4.copper.df
# in EnvStats package.
# (a) Use the t-test and Wilcoxon rank sum test to compare the data from the two
# background wells.

# (b) Which of the two methods is more appropriate for this data? Or would you
# recommend any other method we studied in Stat 414?

```

